language: cpp

os:
    - linux
    - osx

compiler:
    - gcc

env:
    - BUILD_TYPE=Release

before_script:
    - if [ "`uname`" != "Darwin" ] ; then export MOOS_CXX_FLAGS="-fPIC -Wno-long-long"; fi
    - cd ..
    - git clone --depth=1 https://github.com/msis/core-moos
    - cd core-moos
    - mkdir build
    - cd build
    - cmake -DENABLE_EXPORT=ON -DUSE_ASYNC_COMMS=ON -DTIME_WARP_AGGLOMERATION=0.4 -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_CXX_FLAGS=$MOOS_CXX_FLAGS ..
    - cmake --build . --config Release
    - cmake --build . --config Release --target install
    - cd $TRAVIS_BUILD_DIR
    - mkdir build/


script:
    - cd build/
    - cmake -DBUILD_CONSOLE_TOOLS=ON -DBUILD_GRAPHICAL_TOOLS=ON -DBUILD_UPB=ON -DCMAKE_BUILD_TYPE=$BUILD_TYPE ../
    - cmake --build . --config Release

after_script:
    - cmake --build . --config Release --target install